import { jsPDF } from 'jspdf';
import { MODEL_META } from './Modelmeta';

/* ------------------------------------------------------------------ */
/* Report generation — compiles a whole session into one audit-format */
/* PDF. Vector text throughout (not a screenshot), so it stays sharp  */
/* and searchable/selectable at any zoom, which matters for a         */
/* document meant to be submitted rather than just viewed on screen.  */
/* ------------------------------------------------------------------ */

const PAGE = { width: 210, height: 297 }; // A4, mm
const MARGIN = 18;
const CONTENT_WIDTH = PAGE.width - MARGIN * 2;
const GOLD = [212, 168, 67];
const GOLD_DEEP = [148, 108, 22]; // darker gold, readable as text on white
const INK = [22, 22, 26];
const BODY = [55, 55, 60];
const MUTED = [125, 125, 132];
const RULE = [225, 225, 228];

function blobUrlToDataUrl(url) {
  return fetch(url)
    .then((res) => res.blob())
    .then(
      (blob) =>
        new Promise((resolve, reject) => {
          const reader = new FileReader();
          reader.onloadend = () => resolve(reader.result);
          reader.onerror = reject;
          reader.readAsDataURL(blob);
        })
    );
}

function loadImageDims(dataUrl) {
  return new Promise((resolve) => {
    const img = new window.Image();
    img.onload = () => resolve({ width: img.naturalWidth || 1, height: img.naturalHeight || 1 });
    img.onerror = () => resolve({ width: 1, height: 1 });
    img.src = dataUrl;
  });
}

function drawLogoMark(doc, cx, cy, r) {
  doc.setDrawColor(...GOLD);
  doc.setLineWidth(0.5);
  doc.circle(cx, cy, r, 'S');
  doc.line(cx, cy - r - 1.6, cx, cy - r + 1.6);
  doc.line(cx, cy + r - 1.6, cx, cy + r + 1.6);
  doc.line(cx - r - 1.6, cy, cx - r + 1.6, cy);
  doc.line(cx + r - 1.6, cy, cx + r + 1.6, cy);
}

function drawPageHeader(doc) {
  drawLogoMark(doc, MARGIN + 3, 14, 3);
  doc.setFont('courier', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...INK);
  doc.text('SATQUERY AI', MARGIN + 9, 15.5);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  doc.text('GEOSPATIAL ANALYSIS REPORT', PAGE.width - MARGIN, 15.5, { align: 'right' });

  doc.setDrawColor(...GOLD);
  doc.setLineWidth(0.4);
  doc.line(MARGIN, 20, PAGE.width - MARGIN, 20);
}

function drawPageFooter(doc, pageNum, totalPages, refId) {
  doc.setDrawColor(...RULE);
  doc.setLineWidth(0.2);
  doc.line(MARGIN, PAGE.height - 16, PAGE.width - MARGIN, PAGE.height - 16);

  doc.setFont('courier', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(...MUTED);
  doc.text(`REF ${refId}`, MARGIN, PAGE.height - 10);
  doc.text(
    'CONFIDENTIAL \u2014 SYSTEM-GENERATED, SUBJECT TO SECOND-PASS REVIEW',
    PAGE.width / 2,
    PAGE.height - 10,
    { align: 'center' }
  );
  doc.text(`Page ${pageNum} of ${totalPages}`, PAGE.width - MARGIN, PAGE.height - 10, {
    align: 'right',
  });
}

export async function generateSessionReport(session, generatedBy) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const refId = `SQ-${session.id.split('-').slice(-1)[0].toUpperCase()}`;
  const generatedAt = new Date();
  let y = 32;

  const ensureSpace = (needed) => {
    if (y + needed > PAGE.height - MARGIN - 10) {
      doc.addPage();
      y = 32;
    }
  };

  drawPageHeader(doc);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(17);
  doc.setTextColor(...INK);
  const titleLines = doc.splitTextToSize(
    session.title === 'New session' ? 'Untitled session' : session.title,
    CONTENT_WIDTH
  );
  doc.text(titleLines, MARGIN, y);
  y += titleLines.length * 7 + 4;

  const userTurns = session.messages.filter((m) => m.role === 'user').length;
  const agentTurns = session.messages.filter((m) => m.role === 'agent');
  const avgConfidence = agentTurns.length
    ? Math.round(agentTurns.reduce((sum, m) => sum + m.confidence, 0) / agentTurns.length)
    : null;

  const meta = [
    ['Report reference', refId],
    ['Queries submitted', String(userTurns)],
    ['Verified responses', String(agentTurns.length)],
    ['Average confidence', avgConfidence !== null ? `${avgConfidence}%` : '\u2014'],
    ['Generated by', generatedBy || 'Unknown user'],
    ['Generated', generatedAt.toLocaleString()],
  ];
  doc.setFontSize(9);
  meta.forEach(([label, value], i) => {
    const rowY = y + i * 5.5;
    doc.setFont('courier', 'normal');
    doc.setTextColor(...MUTED);
    doc.text(label.toUpperCase(), MARGIN, rowY);
    doc.setFont('courier', 'bold');
    doc.setTextColor(...GOLD_DEEP);
    doc.text(value, MARGIN + 55, rowY);
  });
  y += meta.length * 5.5 + 6;

  doc.setDrawColor(...GOLD);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y, PAGE.width - MARGIN, y);
  y += 9;

  let qIndex = 0;
  for (let i = 0; i < session.messages.length; i++) {
    const m = session.messages[i];
    if (m.role !== 'user') continue;
    qIndex += 1;
    const reply = session.messages[i + 1]?.role === 'agent' ? session.messages[i + 1] : null;

    ensureSpace(16);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11.5);
    doc.setTextColor(...INK);
    doc.text(`Query ${qIndex}`, MARGIN, y);
    y += 6;

    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9.5);
    doc.setTextColor(...BODY);
    const queryLines = doc.splitTextToSize(`\u201c${m.text}\u201d`, CONTENT_WIDTH);
    ensureSpace(queryLines.length * 5);
    doc.text(queryLines, MARGIN, y);
    y += queryLines.length * 5 + 4;

    if (!reply) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(...MUTED);
      ensureSpace(6);
      doc.text('No response recorded for this query.', MARGIN, y);
      y += 10;
      continue;
    }

    if (reply.images?.length) {
      const box = 36;
      ensureSpace(box + 8);
      let x = MARGIN;
      for (const img of reply.images) {
        try {
          const dataUrl = await blobUrlToDataUrl(img.url);
          const dims = await loadImageDims(dataUrl);
          const scale = Math.min(box / dims.width, box / dims.height);
          const w = dims.width * scale;
          const h = dims.height * scale;
          doc.setDrawColor(...RULE);
          doc.setLineWidth(0.3);
          doc.rect(x, y, box, box);
          doc.addImage(dataUrl, x + (box - w) / 2, y + (box - h) / 2, w, h);
          if (img.date) {
            doc.setFont('courier', 'normal');
            doc.setFontSize(6.5);
            doc.setTextColor(...MUTED);
            doc.text(img.date, x + box / 2, y + box + 4, { align: 'center' });
          }
        } catch (e) {
          doc.setDrawColor(...RULE);
          doc.rect(x, y, box, box);
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(7);
          doc.setTextColor(...MUTED);
          doc.text('Image unavailable', x + box / 2, y + box / 2, { align: 'center' });
        }
        x += box + 6;
      }
      y += box + 9;
    }

    ensureSpace(6);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(...INK);
    const answerLines = doc.splitTextToSize(reply.text, CONTENT_WIDTH);
    ensureSpace(answerLines.length * 5);
    doc.text(answerLines, MARGIN, y);
    y += answerLines.length * 5 + 4;

    if (reply.evidence) {
      ensureSpace(8);
      doc.setFont('courier', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(...MUTED);
      const ev = doc.splitTextToSize(reply.evidence, CONTENT_WIDTH);
      doc.text(ev, MARGIN, y);
      y += ev.length * 4.2 + 3;
    }

    const rows = reply.detections
      ? reply.detections.map((d, idx) => [String(idx + 1), d.label, `${d.confidence}%`, `${d.area} km\u00b2`])
      : reply.changeRegions
      ? reply.changeRegions.map((r, idx) => [String(idx + 1), r.label, '\u2014', '\u2014'])
      : [];

    if (rows.length) {
      ensureSpace(rows.length * 5.5 + 10);
      const col = [MARGIN, MARGIN + 9, MARGIN + 118, MARGIN + 152];
      doc.setFont('courier', 'bold');
      doc.setFontSize(7.5);
      doc.setTextColor(...MUTED);
      doc.text('#', col[0], y);
      doc.text('DETECTION', col[1], y);
      doc.text('CONFIDENCE', col[2], y);
      doc.text('AREA', col[3], y);
      y += 3;
      doc.setDrawColor(...RULE);
      doc.setLineWidth(0.2);
      doc.line(MARGIN, y, PAGE.width - MARGIN, y);
      y += 4.5;

      doc.setFont('courier', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(...BODY);
      rows.forEach((r) => {
        ensureSpace(5.5);
        doc.text(r[0], col[0], y);
        doc.text(r[1], col[1], y);
        doc.text(r[2], col[2], y);
        doc.text(r[3], col[3], y);
        y += 5.5;
      });
      y += 3;
    }

    ensureSpace(7);
    doc.setFont('courier', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(...GOLD_DEEP);
    doc.text(
      `${MODEL_META[reply.model].name}  \u00b7  CONFIDENCE ${reply.confidence}%  \u00b7  ${reply.responseTime}s  \u00b7  SECOND REVIEW: PENDING`,
      MARGIN,
      y
    );
    y += 10;

    doc.setDrawColor(...RULE);
    doc.setLineWidth(0.2);
    doc.line(MARGIN, y - 4, PAGE.width - MARGIN, y - 4);
  }

  const totalPages = doc.internal.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    if (p > 1) drawPageHeader(doc);
    drawPageFooter(doc, p, totalPages, refId);
  }

  return { doc, refId };
}